name: guide-design
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - bioconda::guidescan=2.0.0
  - pandas=2.0.3
  - numpy=1.24.3
  - biopython=1.81
  - pybedtools=0.9.1
  - pysam=0.21.0
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - pip:
    - rs3==0.0.6
